<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-05-15 at 06:26:57.
 */


class UserTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var User
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $host = "localhost";
        $db = "tow";
        $user = "towuser";
        $pass = "towpassword";
        $this->database = new PDO("mysql:host=$host;dbname=$db",$user,$pass);
        $this->User = new User($this->database);

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {      
    }



    /**
     * @covers User::checkUsername
     * @todo   Implement testCheckUsername().
     */
    public function testCheckUsername()
    {
        $username = $this->User->checkUsername("stephen");
       
        $this->assertEquals($username, 'Username found');
        
        $username = $this->User->checkUsername("fake");
       
        $this->assertEquals($username, 'Username not found');
    }
    
    /**
     * @covers User::checkEmail
     * @todo   Implement testCheckEmail().
     */
    public function testCheckEmail()
    {
        $email = $this->User->checkEmail("steve@steve.com");
       
        $this->assertEquals($email, 'Email found');
        
        $email = $this->User->checkEmail("fake@steve.com");
       
        $this->assertEquals($email, 'Email not found');
    }

    /**
     * @covers User::checkPassword
     * @todo   Implement testCheckPassword().
     */
    public function testCheckPassword()
    {
        //set Password like it's been pulled from DB
        $this->User->setPassword("password", "fromdb");
        
        //as we set the Password rawly it is now just 'password'
        $this->assertEquals("password" , $this->User->getPassword());
        
        //set Password as a new password this will encrypt the password
        $this->User->setPassword("password");
        
        //as we encrypted as we set password is now '5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8'
        $this->assertEquals("5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8" , $this->User->getPassword());
        
        //check Password with encryption happening
        $test = $this->User->checkPassword("password");
       
        $this->assertTrue($test);
        
        //check Password with encryption using the wrong password
        $test = $this->User->checkPassword("stephen");
       
        $this->assertFalse($test);
    }
    
    /**
     * @covers User::createUser
     * @todo   Implement testCreateUser().
     */
    public function testCreateUser()
    {
        $user = $this->User->createUser("stephena", "password", "fake@steve.com", 5);
       
        $this->assertInstanceOf('User', $user);
     }

    /**
     * @covers User::createUser
     * @todo   Implement testCreateUser().
     */
    public function testSave()
    {
        // Stop here and mark this test as incomplete.
        //$this->markTestIncomplete( 'Skipping Test Save until created a delete');
        
        $this->User->createUser("DBTEST", "password", "DBTEST@steve.com", 5);
        
        $saved = $this->User->save();
       
        $this->assertEquals('saved', $saved);
        
        //Delete 2nd last create
        $this->database->query("DELETE FROM `users` WHERE `username` = 'DBTEST1'");
        //Move last user create to DBTEST1 so we can check it happened
        $this->database->query("UPDATE  `users` SET  `username` =  'DBTEST1', `email` =  'DBTEST21' WHERE `username` =  'DBTEST'");
     }
     
    /**
     * @covers User::loginUser
     * @todo   Implement testLoginUser().
     */
    public function testLoginUser()
    {
        //Good user
        $user = $this->User->loginUser("stephen", "password");
       
        $this->assertInstanceOf('User', $user);
        
        //Wrong username
        $login = $this->User->loginUser("stephena", "password");
       
        $this->assertEquals($login, "Username not found");
        
        //Wrong password
        $login = $this->User->loginUser("stephen", "passwordWrong");
       
        $this->assertEquals($login, "Password Incorrect");
    }
}
